### ISSUE TITLE
Avoid JS for library initial load

### ISSUE THREAD

**Issue by GaryJones** [devinsays/instant-content#6]
The current flow of the library page loading is this:
1. Click on library
2. The PHP loads, as a fairly empty page.
3. The JS kicks in, does an Ajax call, and grabs previous purchases, then updates the page.

There are a few drawbacks to this approach:
1. If JavaScript is disabled they have no way of seeing what their previous purchases are (I realise much of the rest of the plugin relies on JS, but trying to reduce a dependency for basic usage is worth pursuing).
2. There's a delay in loading each time the view the library as the user waits for the API to respond and the result parsed into the DOM, even though the data hasn't changed.
3. The call to the API is not cached, and with lots of users, could create unnecessary scaling issues.
4. A new API call is made when the user paginates forwards or backwards.

A better flow would be:
1. Click on library.
2. Whilst creating the page with PHP, check for a transient of a previous API call, and if it's present, use that to create the list.
3. If it's not present, do a `wp_remote_get()` request to grab the library info, and cache it  in a transient, then use it to create the list.
4. Upon purchase of a new article, clear the transient.

The pagination buttons could also work off of PHP as well, with some JS behaviour on top doing an ajax call so that if JS is enabled, a full page refresh isn't needed (but if it isn't, it will still work with a full page refresh). Make the pagination prev and next standard working links, then use the hijax technique to intercept the click with JS.

**Comment by devinsays** [comment]
Good suggestion.  This library was originally built to store all the purchases in an option (complete other information, like whether it had been imported already or not), but I refactored and went back to a simple ajax call.

Clearing the transient would need to be done when a user clicks the "purchase" button.  There is a chance the user could use the same API key for multiple sites- so there would also need to be a "refresh" button on the library page so the user could also "manually" clear it.
